DROP DATABASE IF EXISTS parties_db;
CREATE DATABASE parties_db;
USE parties_db;

CREATE TABLE clients (
	id INTEGER NOT NULL AUTO_INCREMENT,
	client VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE parties (
	id INTEGER NOT NULL AUTO_INCREMENT,
	party_name VARCHAR(255) NOT NULL,
	party_type VARCHAR(255) NOT NULL,
	party_cost INTEGER NOT NULL,
	client_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (client_id) REFERENCES clients(id)
);
